import { supabase } from '../../config/supabase';
import { Invoice, InvoiceDetail, InvoiceLineItem, InvoiceListItem } from '../../types';
import { InvoiceSchema } from '../../types/schemas';

// ─────────────────────────────────────────────────────────────────────────────
// Raw DB row shapes returned by joined queries
// ─────────────────────────────────────────────────────────────────────────────

type RawInvoiceRow = {
  id: string;
  invoice_number: string;
  order_id: string;
  customer_id: string;
  total_amount: number;
  status: string;
  pdf_url: string | null;
  pdf_generated_at: string | null;
  notes: string | null;
  issued_at: string;
  created_at: string;
  updated_at: string;
};

type RawOrderItemRow = {
  id: string;
  order_id: string;
  menu_item_id: string;
  quantity: number;
  unit_price: number;
  subtotal: number;
  menu_items?: { name: string };
};

type RawUserRow = {
  id: string;
  name: string;
  email: string;
};

// ─────────────────────────────────────────────────────────────────────────────
// WRITE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Insert a new invoice row.
 * invoice_number is auto-generated by a PostgreSQL trigger — do NOT pass it here.
 */
export const insertInvoice = async (payload: {
  order_id: string;
  customer_id: string;
  total_amount: number;
}): Promise<Invoice> => {
  const { data, error } = await supabase
    .from('invoices')
    .insert(payload)
    .select('*')
    .single();

  if (error || !data) {
    throw new Error(`Failed to create invoice: ${error?.message ?? 'No data returned'}`);
  }

  return InvoiceSchema.parse(data);
};

/**
 * Save the Supabase Storage path for the generated PDF and stamp pdf_generated_at.
 */
export const updateInvoicePdfPath = async (
  invoiceId: string,
  pdfStoragePath: string
): Promise<Invoice> => {
  const { data, error } = await supabase
    .from('invoices')
    .update({
      pdf_url: pdfStoragePath,
      pdf_generated_at: new Date().toISOString(),
    })
    .eq('id', invoiceId)
    .select('*')
    .single();

  if (error || !data) {
    throw new Error(`Failed to update invoice PDF path: ${error?.message ?? 'No data returned'}`);
  }

  return InvoiceSchema.parse(data);
};

// ─────────────────────────────────────────────────────────────────────────────
// READ — single row
// ─────────────────────────────────────────────────────────────────────────────

/** Fetch a plain invoice row by its primary key. */
export const findInvoiceById = async (id: string): Promise<Invoice | null> => {
  const { data, error } = await supabase
    .from('invoices')
    .select('*')
    .eq('id', id)
    .limit(1);

  if (error) {
    throw new Error(`Failed to fetch invoice: ${error.message}`);
  }

  if (!data || data.length === 0) return null;
  return InvoiceSchema.parse(data[0]);
};

/** Fetch a plain invoice row by the linked order_id (UNIQUE constraint, returns at most one). */
export const findInvoiceByOrderId = async (orderId: string): Promise<Invoice | null> => {
  const { data, error } = await supabase
    .from('invoices')
    .select('*')
    .eq('order_id', orderId)
    .limit(1);

  if (error) {
    throw new Error(`Failed to fetch invoice by order: ${error.message}`);
  }

  if (!data || data.length === 0) return null;
  return InvoiceSchema.parse(data[0]);
};

/**
 * Fetch full invoice detail for a given invoice id:
 * invoice row + customer info + order line items (with menu item names).
 */
export const findInvoiceDetail = async (id: string): Promise<InvoiceDetail | null> => {
  // 1. Fetch the invoice row
  const { data: invData, error: invError } = await supabase
    .from('invoices')
    .select('*')
    .eq('id', id)
    .limit(1);

  if (invError) {
    throw new Error(`Failed to fetch invoice detail: ${invError.message}`);
  }

  if (!invData || invData.length === 0) return null;

  const raw = invData[0] as RawInvoiceRow;
  const invoice = InvoiceSchema.parse(raw);

  // 2. Fetch customer info
  const { data: userData, error: userError } = await supabase
    .from('users')
    .select('id, name, email')
    .eq('id', invoice.customer_id)
    .limit(1);

  if (userError) {
    throw new Error(`Failed to fetch customer for invoice: ${userError.message}`);
  }

  const customer = ((userData ?? []) as RawUserRow[])[0];

  // 3. Fetch order items with menu item names (prices already snapshotted)
  const { data: itemsData, error: itemsError } = await supabase
    .from('order_items')
    .select('*, menu_items(name)')
    .eq('order_id', invoice.order_id);

  if (itemsError) {
    throw new Error(`Failed to fetch order items for invoice: ${itemsError.message}`);
  }

  const items: InvoiceLineItem[] = ((itemsData ?? []) as RawOrderItemRow[]).map((row) => ({
    name: row.menu_items?.name ?? 'Unknown item',
    quantity: row.quantity,
    unit_price: row.unit_price,
    subtotal: row.subtotal,
  }));

  return {
    ...invoice,
    customer_name: customer?.name ?? 'Unknown',
    customer_email: customer?.email ?? '',
    items,
  };
};

// ─────────────────────────────────────────────────────────────────────────────
// READ — list
// ─────────────────────────────────────────────────────────────────────────────

/** List all invoices for a specific customer, newest first. */
export const findInvoicesByCustomer = async (
  customerId: string,
  filters: { status?: string; limit: number; offset: number }
): Promise<InvoiceListItem[]> => {
  let query = supabase
    .from('invoices')
    .select('id, invoice_number, order_id, total_amount, status, issued_at')
    .eq('customer_id', customerId)
    .order('issued_at', { ascending: false })
    .range(filters.offset, filters.offset + filters.limit - 1);

  if (filters.status) {
    query = query.eq('status', filters.status);
  }

  const { data, error } = await query;

  if (error) {
    throw new Error(`Failed to fetch customer invoices: ${error.message}`);
  }

  return (data ?? []) as InvoiceListItem[];
};
